server:
  port: 9005
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9094
      group-id: test-kafka
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.example.util.CustomDeserializer
      properties:
        spring.json.trusted.packages: "*"

    producer:
      bootstrap-servers: localhost:9094
      value-serializer: org.example.util.CustomSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer


topic:
  name:
    producer: topic-test-1
    consumer: topic-test-1

clickhouse:
  host: localhost
  port: 18213
  database: measurement
  user: default
  password:

